services:
  llm-workshop-api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

  llm-workshop-cli:
    extra_hosts:
      - "host.docker.internal:host-gateway"
